# Generated by Django 2.2.1 on 2019-11-15 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0004_auto_20191115_0621'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='title',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
