# Generated by Django 2.2.1 on 2019-11-15 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0005_student_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='title',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
