# Generated by Django 2.2.1 on 2019-11-15 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0006_auto_20191115_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='title',
        ),
    ]
