# Generated by Django 2.2.1 on 2019-11-15 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0007_remove_student_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='code_no',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
